### ISSUE TITLE
CalendarError: Unable to ascertain calendar

### ISSUE THREAD

**Issue by ValueRaider** [maread99/market_prices#133] opened 2023-01-07 21:35 UTC
```
PricesYahoo("VUX.V")
```

> market_prices.errors.CalendarError: Unable to ascertain calendar for symbol 'VUX.V'

https://finance.yahoo.com/quote/VUX.V?p=VUX.V&.tsrc=fin-srch

**Comment by maread99** [comment] 2023-01-09 10:46
Hi @ValueRaider

This error is raised when the `PricesYahoo` class is unable to map a symbol to an appropriate calendar. The symbol can still be included by passing an `exchange_calendars.ExchangeCalendar` instance to the `calendars` kwarg (see the `PricesYahoo` class [doc](https://github.com/maread99/market_prices/blob/319da1cbff341e3983b674e64016ae2c552797d1/src/market_prices/prices/yahoo.py#L38) and **Calendars** section of the [prices tutorial](https://github.com/maread99/market_prices/blob/master/docs/tutorials/prices.ipynb)).

The class can't ascertain a calendar for VUX.V because there's no mapping for the TSX Venture Exchange. It should just be a matter of adding `"TSXV": "XTSE"` to the [yahoo_config mappings](https://github.com/maread99/market_prices/blob/319da1cbff341e3983b674e64016ae2c552797d1/src/market_prices/prices/config/config_yahoo.py#L31)]. I will do this.

Are there any other exchanges that you've come across that aren't mapping?

**Comment by ValueRaider** [comment] 2023-01-10 18:07
I'll check other exchanges.

**Comment by ValueRaider** [comment] 2023-01-21 19:53
I've tested all 26 exchanges I monitor:

Other exchanges with same error:
- Canada CSE, e.g. Yahoo ticker "VIK.CN"
- Israel Tel Aviv, e.g. Yahoo ticker "ESLT.TA"

ASX exchange (e.g. ticker "29M.AX" raises a different calendar error:
> 29M.AX failed: Calendar 'XASX' is too short to support all available intraday price history. Calendar starts '2021-06-18 00:00:00+00:00' whilst earliest minute for which intraday price history is available is '2021-01-21 19:45:00+00:00' (all calendars must be valid over at least the period for which intraday price data is available).

**Comment by maread99** [comment] 2023-01-24 22:53
Thanks ValueRaider.

I've [added the following mappings](https://github.com/maread99/market_prices/pull/138/commits/3dafa79633e8655136b39f3f33e9c71aa7286cb4):
* Tel Aviv to XTAE
* 'TSX Venture Exchange' to XTSE
* 'Canadian Securities Exchange' to XTSE

The 29M.AX `CalendarTooShortError` error was a separate issue, caused by a bug fixed in #138. Instruments that trade on the ASX exchange should be mapping fine.

The new mappings / bug fix are all included to the latest release 0.10.

**Closed by maread99** 2023-01-24 22:53 UTC
Labels: TODO
